Repository Studio-Yandex-Practicum/spread_wings_bot, pull requests merged in 2023-07, with the labels that each got.

#96 Change imports to absolute
  src/bot/__init__.py
  src/bot/apps.py
  src/bot/bot.py
  src/bot/urls.py
  src/bot/views.py
  src/utils/db_fixtures/factories/contact_factories.py
  src/utils/db_fixtures/factories/question_factories.py
Labels: Refactor

#92 connect django and postgresql
  .env.example
  .github/workflows/deploy-bot-on-stage.yml
  README.md
  infra/dev/docker-compose.local.yaml
  infra/dev/docker-compose.stage.yaml
  poetry.lock
  pyproject.toml
  src/config/settings.py
Labels: Feature

#98 Remove mysql
  poetry.lock
  pyproject.toml
  requirements/develop.txt
  requirements/production.txt
  src/bot/services.py
  src/utils/db/__init__.py
  src/utils/db/crud/__init__.py
  src/utils/db/crud/extract.py
  src/utils/db/db.py
  src/utils/db/schemas/__init__.py
  src/utils/db_fixtures/filldb.py
  src/utils/db_fixtures/queries.py
Labels: Refactor

#101 Fix #88 stage workflow
  .env.example
  .github/workflows/deploy-bot-on-stage.yml
  Makefile
  infra/dev/docker-compose.stage.yaml
  poetry.lock
  pyproject.toml
  requirements/develop.txt
  requirements/production.txt
  src/config/settings.py
Labels: Fix

#107 Feature/upmenu delete
  src/bot/bot.py
  src/bot/handlers/main_handlers.py
  src/bot/handlers/service_handlers.py
Labels: Fix

#105 add BotSettings model
  src/bot_settings/__init__.py
  src/bot_settings/admin.py
  src/bot_settings/apps.py
  src/bot_settings/migrations/0001_initial.py
  src/bot_settings/migrations/0002_add_donation_url.py
  src/bot_settings/migrations/__init__.py
  src/bot_settings/models.py
  src/config/settings.py
Labels: Feature

#114 fix db connection params
  .env.example
  src/config/settings.py
Labels: Bug

#115 change assistance keyboard to async
  poetry.lock
  pyproject.toml
  requirements/develop.txt
  requirements/production.txt
  src/bot/__init__.py
  src/bot/apps.py
  src/bot/bot.py
  src/bot/constants/urls.py
  src/bot/handlers/ask_question.py
  src/bot/handlers/main_handlers.py
  src/bot/keyboards/assistance.py
Labels: Feature

#116 update mailing system to django style
  .env.example
  .github/workflows/deploy-bot-on-stage.yml
  src/bot/handlers/ask_question.py
  src/bot/models_pydantic/users_questions.py
  src/config/settings.py
  src/core/mailing.py
  src/core/validators.py
  src/templates/email.html
  src/utils/mailing.py
Labels: Refactor
