Repository Studio-Yandex-Practicum/spread_wings_bot, pull requests merged in 2023-08, with the labels that each got.

#124 localized
  src/config/settings.py
  src/users/admin.py
Labels: Refactor

#126 Feature/migrate collectstatic
  Makefile
  infra/dev/docker-compose.stage.yaml
  src/bot/constants/commands.py
Labels: Feature

#133 fix question type in common questions
  src/bot/constants/types_of_assistance.py
  src/bot/handlers/assistance.py
  src/bot/models_pydantic/users_questions.py
Labels: Bug

#146 Автоматизировал развертку бота для локальной разработки
  Makefile
Labels: Feature

#150 add nginx configuration for serving static
  .gitignore
  Dockerfile
  infra/dev/docker-compose.stage.yaml
  infra/dev/nginx.stage.conf
  infra/dev/redis.conf
  infra/init.sh
  src/config/urls.py
Labels: Feature

#152 feature/141 get region questions from db
  src/bot/bot.py
  src/bot/constants/patterns.py
  src/bot/handlers/assistance.py
  src/bot/keyboards/assistance.py
  src/bot/keyboards/assistance_types.py
  src/bot/keyboards/utils/__init__.py
  src/bot/keyboards/utils/telegram_pagination.py
  src/bot/models.py
  src/core/management/commands/filldb.py
Labels: Feature

#145 refactor of constants dir
  src/bot/bot.py
  src/bot/constants/back_functions.py
  src/bot/constants/buttons.py
  src/bot/constants/commands.py
  src/bot/constants/contacts.py
  src/bot/constants/list_of_questions.py
  src/bot/constants/messages.py
  src/bot/constants/patterns.py
  src/bot/constants/regions.py
  src/bot/constants/states.py
  src/bot/constants/types_of_assistance.py
  src/bot/handlers/ask_question.py
  src/bot/handlers/assistance.py
  src/bot/handlers/back_handler.py
  src/bot/handlers/main_handlers.py
  src/bot/handlers/service_handlers.py
  src/bot/keyboards/assistance.py
  src/bot/keyboards/assistance_types.py
Labels: Refactor

#166 Подтягивать параметры конфигурации Nginx из env
  .github/workflows/deploy-bot-on-stage.yml
  infra/dev/docker-compose.stage.yaml
  infra/dev/nginx.stage.conf.template
Labels: Feature

#165 added the ability to get coordinator's contacts from db
  src/bot/constants/messages.py
  src/bot/handlers/assistance.py
  src/bot/migrations/0009_alter_coordinator_phone_number_and_more.py
  src/bot/models.py
Labels: Fix, Feature

#175 Feature/155 testing bot with pytest
  .github/workflows/codestyle_pep8.yml
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  requirements/develop.txt
  requirements/production.txt
  src/tests/__init__.py
  src/tests/unit/__init__.py
  src/tests/unit/test_handlers/__init__.py
  src/tests/unit/test_handlers/conftest.py
  src/tests/unit/test_handlers/test_help.py
  src/tests/unit/test_handlers/test_receive_assistance.py
  src/tests/unit/test_handlers/test_select_assistance.py
  src/tests/unit/test_handlers/test_select_type_of_help.py
  src/tests/unit/test_handlers/test_start.py
  tests/conftest.py
  tests/fixtures/fixture_data.py
  tests/test_bot.py
Labels: Feature

#183 178 Move tests to separate action file
  .github/workflows/codestyle_pep8.yml
  .github/workflows/deploy-bot-on-stage.yml
  .github/workflows/run_pytest.yml
  Makefile
  src/tests/unit/test_handlers/conftest.py
  src/tests/unit/test_handlers/test_help.py
  src/tests/unit/test_handlers/test_receive_assistance.py
  src/tests/unit/test_handlers/test_select_assistance.py
  src/tests/unit/test_handlers/test_start.py
Labels: Feature

#186 Feature/155 testing bot with pytest
  .github/workflows/codestyle_pep8.yml
  Makefile
  src/tests/unit/test_handlers/test_select_assistance.py
  src/tests/unit/test_handlers/test_start.py
Labels: Refactor

#210 Bugfix/209 return default path to admin configure nginx redirect
  infra/dev/nginx.stage.conf.template
  infra/prod/nginx.prod.conf.template
  src/config/urls.py
Labels: Fix

#230 update widget for Question/FundProgram -> Region
  src/bot/admin.py
  src/bot/forms.py
Labels: Feature

#235 Добавил отметку главного координатора
  src/bot/admin.py
  src/bot/handlers/show_objects.py
  src/bot/migrations/0004_alter_coordinator_options_coordinator_is_chief.py
  src/bot/models.py
  src/bot/validators.py
Labels: Feature
